### ISSUE TITLE
~

### ISSUE THREAD

**Issue by xairry** [luanfujun/deep-painterly-harmonization#26]
cuda_utils.cu:8:17: fatal error: THC.h: 没有那个文件或目录
compilation terminated.
makefile:11: recipe for target 'libcuda_utils.so' failed
make: *** [libcuda_utils.so] Error 1

**Comment by caijicz** [comment]
Compile cuda_utils.cu (Adjust PREFIX and NVCC_PREFIX in makefile for your machine) 
把文件里的PREFIX和NVCC_PREFIX改成你电脑里对应的路径

**Comment by ganggangzhou** [comment]
我也碰到了这个问题，路径都已经改了，我查看torch/install/include里面没有THC文件。  请问你解决这个问题了吗？
