### ISSUE TITLE
Conflicts between paper and the code

### ISSUE THREAD

**Issue by HenryJia** [luanfujun/deep-painterly-harmonization#29]
Hi I'm reading through your neural_paint.lua and I'm noticing a lot of conflicts
At https://github.com/luanfujun/deep-painterly-harmonization/blob/master/neural_paint.lua#L151
You use conv5_1 as your reference layer, yet in the paper, you say that conv4_1 was the optimum

At line 155, you use the resized style image as your reference guide, but in the paper, you again say that conv4_1 is the reference layer

At line 168, it appears you are storing the un-matched style features and not the matched features and are completely ignoring the matched and then consistency refined features

Can you explain these conflicts?

Thanks

**Comment by tombohub** [comment]
@HenryJia do this conflict affect the quality of final image?

**Comment by HenryJia** [comment]
I've no idea, because I was originally using this as a reference code to write my own implementation, but I've been unable to do so due to the vagueness of certain parts in the paper, my unfamiliarity with torch and the conflicting parts here

**Comment by cikatomo** [comment]
@HenryJia I am researching and I think it has something to do because patchmatch was compiled for matlab, but octave can't use that files. we need to compile for octave. Do you know anything about octave or matlab? Ive never used that

**Comment by luanfujun** [comment]
line 63: local layers = string.format('relu1_1,relu2_1,relu3_1,relu4_1'):split(",")
So conv5_1 wasn't used, it was just some comments I didn't clean up.

**Comment by luanfujun** [comment]
@HenryJia Maybe try some other people's implemetation?
https://github.com/sarahmfrost/manumorph
https://github.com/sgugger/Deep-Learning/blob/master/DeepPainterlyHarmonization.ipynb

**Comment by HenryJia** [comment]
Considering it's been 2 years since I opened the issue, I'm currently not trying to implement this anymore
