### ISSUE TITLE
/usr/bin/ld: cannot find -lluajit

### ISSUE THREAD

**Issue by Hongiee2** [luanfujun/deep-painterly-harmonization#43]
![image](https://user-images.githubusercontent.com/46617803/80934231-2d575b80-8e02-11ea-924e-72ca6f762991.png)

torch & lua 5.1 are installed

But still not working

May I get some advice 

having trouble for 3 days...

@luanfujun

**Comment by AIaesthetic** [comment]
same issue. did you solve it?
