### ISSUE TITLE
"attempt to index a nil value" while trying to reproduce the results

### ISSUE THREAD

**Issue by 2m** [luanfujun/deep-painterly-harmonization#5]
I get

```
luajit: neural_paint.lua:140: attempt to index a nil value
stack traceback:
        neural_paint.lua:140: in function 'main'
        neural_paint.lua:739: in main chunk
        [C]: in function 'dofile'
        /usr/bin/th:150: in main chunk
        [C]: at 0x00404680
```

while trying to reproduce the results while folllowing the directions in the README.

Full logs:
<details>
<pre>
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Running optimization with L-BFGS
<optim.lbfgs>   creating recyclable direction/step/history buffers
<optim.lbfgs>   function value changing less than tolX
Gpu, idx      =         0       1
idx=0, classified label=Art Nouveau (Modern), weight=1.203930
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Working on patchmatch layer     4       :       relu4_1
luajit: neural_paint.lua:140: attempt to index a nil value
stack traceback:
        neural_paint.lua:140: in function 'main'
        neural_paint.lua:739: in main chunk
        [C]: in function 'dofile'
        /usr/bin/th:150: in main chunk
        [C]: at 0x00404680
</pre>
</details>

**Comment by luanfujun** [comment]
This is interesting. From your full log I don't see the feature extraction code part running (line 113-127 in ``neural_paint.lua``. Could you add some printing information in that part to ensure it has been executed?

**Comment by 2m** [comment]
I printed out `#cnn` just before this loop

https://github.com/luanfujun/deep-painterly-harmonization/blob/4db7836fa0e060322645700fb3a0cd0be89c27ab/neural_paint.lua#L113

and it was `0`.

**Comment by 2m** [comment]
The caffemodel checksum seems to be fine:

```
➜  deep-painterly-harmonization git:(master) ✗ md5sum models/VGG_ILSVRC_19_layers.caffemodel
b5c644beabd7cf06bdd9065cfd674c97  models/VGG_ILSVRC_19_layers.caffemodel
```

**Comment by luanfujun** [comment]
I see. What about the file ``VGG_ILSVRC_19_layers_deploy.prototxt``: ``ccbbdda59210208be39f8974f5b5765e``? 

If they also match, I suspect it to be the problem from ``loadcaffe`` package. Can you run:
```
loadcaffe.load(params.proto_file, params.model_file, 'nn')
```
in CPU model after reinstalling it? 

Thanks!
Fujun

**Comment by 2m** [comment]
Yea, the prototxt also matches:

```
➜  deep-painterly-harmonization git:(master) ✗ md5sum models/VGG_ILSVRC_19_layers_deploy.prototxt
ccbbdda59210208be39f8974f5b5765e  models/VGG_ILSVRC_19_layers_deploy.prototxt
```

Can you elaborate more on

> in CPU model after reinstalling it?

I do not have much experiance with `loadcaffe`. :)

**Comment by luanfujun** [comment]
Sorry. I mean re-installing loadcaffe using: ``luarocks install loadcaffe`` and load the VGG19 in CPU mode. 

I just ran this command on an ubuntu 16.04: 
![loadcaffe_screenshot](https://user-images.githubusercontent.com/3760952/38791873-444f7b94-4118-11e8-8e9e-5f80fb3942c7.png)

Based on your previous full log, it seems our ``libprotobuf`` version might be different since mine prints the warning message. Are you using Mac OSX? I have only tested the code in ubuntu 16.04 LTS currently.

**Comment by luanfujun** [comment]
Can you call ``cnn:get(i)`` after loading it? If so, a simple yet ugly workaround for this would be hardcoding the number of layers to 46 since VGG-19 is fixed.

**Comment by JangminSon** [comment]
I got same Issue.
![image](https://user-images.githubusercontent.com/27252283/39036110-88c5e11c-44b7-11e8-8099-2dae3507c039.png)

I've checked md5checksum.
I think loadcaffe does load models but it doesn't look like variable cnn has the data

Can you tell me any idea ?

**Comment by JangminSon** [comment]
![image](https://user-images.githubusercontent.com/27252283/39036391-4480feb4-44b8-11e8-815e-ca9868659446.png)
It looks like #cnn is 0 so it doesn't goes into for statement at the line num166 and error occurs at line 144~

Please help me with this issue

**Comment by luanfujun** [comment]
What about replacing ```#cnn``` with ```cnn:size()```?

**Comment by 2m** [comment]
That was it! Now it works! Thank you very much for the hint.
