### ISSUE TITLE
a working 2022 colab!

### ISSUE THREAD

**Issue by eyaler** [luanfujun/deep-painterly-harmonization#63]
You guys asked for it! building on @marcduda 's efforts, here is a 2022 fully working colab with minimal GUI. it can also calculate the mask for you - just upload the naive and target images and play with the style weight (as the wikiart predictor was never released afaiu).
https://colab.research.google.com/gist/eyaler/5303782669fb43510d398bd346c6e3e6/deep-painterly-harmonization.ipynb

**Comment by SebstianZ28** [comment]
Hi, can I ask you how to fix this error:
Installing https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec... switching to 'build' mode
Cloning into 'loadcaffe'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Error: Failed cloning git repository.

**Comment by heartlocket** [comment]
Thanks for sharing this. However the upload image button seems broken to me.

Also, when I try replacing the sample images with my onw, i run into this error:
error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

any idea?

**Comment by eyaler** [comment]
works for me. this error may be due to manual upload of files that was not complete

**Comment by Jelle50** [comment]
Has anyone managed to solve this? I get the same problem while running this in google colab. Even if I use the exact same input data from the examples it doesn't do anything.

It has problems running the "final_im = cv2.imread(final)" line because there is no final file to read. In this case it would be "results/rushmore_final_res.png". But the results folder is completely empty.

**Comment by accable** [comment]
This does not work. final_im requires an image to be saved and later read but since there aren't any, the code would throw an error. 

Assuming the final_im is from dilated_im also causes more problems down the road.

**Comment by eyaler** [comment]
on jan 2023 google updated colab from ubuntu 18 to 20 and later to 22. these are not supported by cuda 10 so i dont have an easy way to fix this
