### ISSUE TITLE
Will it have  a pytorch version?

### ISSUE THREAD

**Issue by a1324321** [luanfujun/deep-painterly-harmonization#7]
Will it have  a pytorch version? I would very appreciate it.

**Comment by luanfujun** [comment]
Currently no... 😂

**Comment by GuohongLi** [comment]
Maybe, a tensorflow or pytorch version will be welcomed. Thx

**Comment by a1324321** [comment]
😂

**Comment by ProGamerGov** [comment]
Deep Painterly Harmonization is based on [Neural-Style](https://github.com/jcjohnson/neural-style), which was written in Lua. If you wanted to convert it to PyTorch, I converted Justin Johnson's Neural-Style to PyTorch a while back here: https://github.com/ProGamerGov/neural-style-pt. I tried to mimic the original Lua code as much as possible, so it should be pretty easy to rebuilt Deep Painterly Harmonization off of it if you know both Python and Lua.
