### ISSUE TITLE
Get error "/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=30 : unknown error"

### ISSUE THREAD

**Issue by bowlderstudio** [luanfujun/deep-painterly-harmonization#8]
I got error when I run "python gen_all.py". Could you give any help to this problem?

**Comment by bowlderstudio** [comment]
More detailed information:
[C]: in function 'error'
/home/.../torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
neural_gram.lua:9: in main chunk
[C]: in function 'dofile'
...nshi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00405d50

**Comment by luanfujun** [comment]
``neural_gram.lua:9`` is ``require 'cutorch'``. Could you run ``th`` in terminal and then ``require 'cutorch'`` in torch to see if this package can be loaded? You can install cutorch using: ``luarocks install cutorch`` (but do ``luarocks install torch`` first to update torch).

**Comment by luanfujun** [comment]
Great! Closing this issue...
