### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [luanfujun/deep-painterly-harmonization#9]
Hello, I would like to design a logo for your software. I can make some ideas if you are interested? Do you have something on your mind for your logo?
Greetings
Nuno

**Comment by luanfujun** [comment]
Thanks man😂 what idea do u have

**Comment by luanfujun** [comment]
The goal of this project is to blend an object into a painting by harmonizing the color and texture, such that the compositing looks natural and stylized. Challenges and corresponding solutions are:

1. Semantically meaningful texture. Such as pasting a face to monalisa, you should also use only the face texture to harmonize the foreground. This inspires us to use deep features for semantic matching. What if there is no strong correlations regarding semantic context between foreground object and painting? This inspires us to use two-step algorithm to ensure robustness.

2. Paintings have different stylization levels. For example, Cubism is strongly stylized with sharp facets, while Baroque is relatively realistic. This inspires us to train a CNN to estimate the stylization level (or more generally speaking, painting types) so we can adjust weights accordingly.

Not sure if those answer your question. You can contact me by email for more details if you like: fujun@cs.cornell.edu :-/
